import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";

const jetBrains = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrains.variable} font-jetbrains-mono grid grid-rows-[auto_1fr] min-h-screen`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
